platform :ios, '8.0'

target 'EasyReact_Example' do
  use_frameworks!
  pod 'EasyReact', :path => '../'
  target 'EasyReact_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
end

target 'Benchmark' do
    use_frameworks!
    pod 'EasyReact', :path => '../'
    pod 'ReactiveCocoa', '2.5'
    pod 'RxSwift'
end
